version: '3'            
                        
services:               
  organizzesync:     
    build: .        
    restart: always     
    volumes:            
      - .:/server
      - /usr/share/zoneinfo/America/Cuiaba:/etc/localtime:ro       
    ports:              
      - "6556:6556"     
    
